name: sccf
description: "A new Flutter project."
publish_to: "none"

version: 1.0.0+1

environment:
  sdk: ^3.7.2

dependencies:
  flutter:
    sdk: flutter
  provider: ^6.0.5
  intl: ^0.20.2
  shared_preferences: ^2.0.15
  image_picker: ^1.1.2
  google_fonts: ^6.1.0
  flutter_screenutil: ^5.9.0
  get: ^4.6.6
  flutter_svg: ^2.0.7
  lottie: ^3.1.0
  cached_network_image: ^3.3.0
  window_size: ^0.1.0
  simple_shadow: ^0.3.0
  http: ^1.1.0
  flutter_dotenv: ^5.1.0
  csv: ^5.0.0
  file_picker: ^5.2.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true
  assets:
    - .env
