// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAlCrts4L8cM_rKte8U4SSUV0a5Jo_EUPI',
    appId: '1:684716408090:web:0ddc41a04b4dd1d45ac0a3',
    messagingSenderId: '684716408090',
    projectId: 'sccf-97823',
    authDomain: 'sccf-97823.firebaseapp.com',
    storageBucket: 'sccf-97823.firebasestorage.app',
    measurementId: 'G-TGLHE2HZQS',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBeF4aL-Q_9FTGOqGMLKx8HJqLKjEa1nUs',
    appId: '1:684716408090:android:a76c1d9f5b6b43425ac0a3',
    messagingSenderId: '684716408090',
    projectId: 'sccf-97823',
    storageBucket: 'sccf-97823.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyD6ff2F1xhsvi59b_SWCiAG9ss5_9muAwY',
    appId: '1:684716408090:ios:88b71839280c38d05ac0a3',
    messagingSenderId: '684716408090',
    projectId: 'sccf-97823',
    storageBucket: 'sccf-97823.firebasestorage.app',
    iosBundleId: 'com.example.sccf',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyD6ff2F1xhsvi59b_SWCiAG9ss5_9muAwY',
    appId: '1:684716408090:ios:88b71839280c38d05ac0a3',
    messagingSenderId: '684716408090',
    projectId: 'sccf-97823',
    storageBucket: 'sccf-97823.firebasestorage.app',
    iosBundleId: 'com.example.sccf',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAlCrts4L8cM_rKte8U4SSUV0a5Jo_EUPI',
    appId: '1:684716408090:web:2c4e10c4a424dc925ac0a3',
    messagingSenderId: '684716408090',
    projectId: 'sccf-97823',
    authDomain: 'sccf-97823.firebaseapp.com',
    storageBucket: 'sccf-97823.firebasestorage.app',
    measurementId: 'G-95Y0BB6WNF',
  );
}
